apiVersion: v1
baseDomain: sokube.io
metadata:
  name: okd

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODViOTU5NjdkNGJlNDBiNDk3MDNhYzYwYmIxNjIzY2M6V1BTRzZERllKOVYwOEZEQlQ5Q1o0TFFWQTdQNzRLWkI4Q0NWS1NUVEc1NUhERUNWSVpTNjM3U0xaVUQ1SjVPUA==","email":"sami.amoura@sokube.ch"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODViOTU5NjdkNGJlNDBiNDk3MDNhYzYwYmIxNjIzY2M6V1BTRzZERllKOVYwOEZEQlQ5Q1o0TFFWQTdQNzRLWkI4Q0NWS1NUVEc1NUhERUNWSVpTNjM3U0xaVUQ1SjVPUA==","email":"sami.amoura@sokube.ch"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE1YjBjZTNkLTZiZTYtNDNiYy05YjA5LTVlZjY5ZmVhM2I3YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpOV1JtTjJKbE56QmtNelEwTlRkbFlqaGpZamczWVdRM05EQm1Oamt4WlNKOS5ubGlkSkZPNEptR0h1N2JnQ0JCNWpUWG1kVEx0eHh4T0V1NWRRRl9hOUp4T0tLLXpCN3NnXzI3ak1yX1EyOGl6M3VqN3kzanJJZVVfeWI5Zm9BTW9SN2RQQjRPQ0lObERyYXIxM3VUY2pQLXhtcGt4NUdXVmxoSFhZLWViWkY0M2g2MnpTNVF1Z2hjWGJvcHVMdXlUQ1UzczJLb1ZUWndfcWZvNjUwbkVBTmMweVVzeVpMMDlybGNRbEJseXhsamN5b0tnbFRXT092NFIwX0JWdWVBVVAxb0RkMS1BZGVvVm5ueDkxenJGQUNlcHE5QU9TRkpEVGZaZXRkbkY1UFdHSDROMUVFTUROdU5CNmFEZDV6bWJubWxWYXMtOTFRWVdfQjI3UDk3TWlZYkZFMlNGcld5NE1Db2dGdzE1M2sxNmJVajZ0NC1KcjhtNTlQbTV6c0plSkN6R25QalFRbUdUeERmcVNOSnBNMzlxY1dPQlVBUVQzTDQ4a3puSHNpQTlXWmtyRnVaV2xQNkxMbFBSWW15eTBHb2JSa3pJcGdabjJsTWlVT09LWFlGR1NtSVVJbGduSU1UNGxEaGNLdGZLVmtEUlJGZHpSY0Rsak9nS2c0UFZ4QUlBRi1NSW9lYmMxc2hORTdVMm5Vei1xdjNrSEhFblRPdWhvUF83eGZsQVU0MS1fMnZXSXAwc0J3U19pWUN5SE5fVE5NeUFsQ1lDWjFRSE1LU0ZEZ0FIYWdjZFItR2NtUVA2OTJrakx6THFYUG5WeEJDOENBTzhyNFk0eE91SFFMeGt4NG8yMjdiMFVBVnB5MVpnMDVRNHJpWFJQZGdUTmY3SFFLcF9xRUtoYzduVDk5TEVmeHhNdEdiblNGeWswa0lxS2RhSVdTZW40ZkViNHc2SzRmQQ==","email":"sami.amoura@sokube.ch"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE1YjBjZTNkLTZiZTYtNDNiYy05YjA5LTVlZjY5ZmVhM2I3YTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpOV1JtTjJKbE56QmtNelEwTlRkbFlqaGpZamczWVdRM05EQm1Oamt4WlNKOS5ubGlkSkZPNEptR0h1N2JnQ0JCNWpUWG1kVEx0eHh4T0V1NWRRRl9hOUp4T0tLLXpCN3NnXzI3ak1yX1EyOGl6M3VqN3kzanJJZVVfeWI5Zm9BTW9SN2RQQjRPQ0lObERyYXIxM3VUY2pQLXhtcGt4NUdXVmxoSFhZLWViWkY0M2g2MnpTNVF1Z2hjWGJvcHVMdXlUQ1UzczJLb1ZUWndfcWZvNjUwbkVBTmMweVVzeVpMMDlybGNRbEJseXhsamN5b0tnbFRXT092NFIwX0JWdWVBVVAxb0RkMS1BZGVvVm5ueDkxenJGQUNlcHE5QU9TRkpEVGZaZXRkbkY1UFdHSDROMUVFTUROdU5CNmFEZDV6bWJubWxWYXMtOTFRWVdfQjI3UDk3TWlZYkZFMlNGcld5NE1Db2dGdzE1M2sxNmJVajZ0NC1KcjhtNTlQbTV6c0plSkN6R25QalFRbUdUeERmcVNOSnBNMzlxY1dPQlVBUVQzTDQ4a3puSHNpQTlXWmtyRnVaV2xQNkxMbFBSWW15eTBHb2JSa3pJcGdabjJsTWlVT09LWFlGR1NtSVVJbGduSU1UNGxEaGNLdGZLVmtEUlJGZHpSY0Rsak9nS2c0UFZ4QUlBRi1NSW9lYmMxc2hORTdVMm5Vei1xdjNrSEhFblRPdWhvUF83eGZsQVU0MS1fMnZXSXAwc0J3U19pWUN5SE5fVE5NeUFsQ1lDWjFRSE1LU0ZEZ0FIYWdjZFItR2NtUVA2OTJrakx6THFYUG5WeEJDOENBTzhyNFk0eE91SFFMeGt4NG8yMjdiMFVBVnB5MVpnMDVRNHJpWFJQZGdUTmY3SFFLcF9xRUtoYzduVDk5TEVmeHhNdEdiblNGeWswa0lxS2RhSVdTZW40ZkViNHc2SzRmQQ==","email":"sami.amoura@sokube.ch"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/dLamL6Kv1qLrLAiDZCAJcVrzVIswM+SIfuc+kBUh8W6VeQZTEjtGaKKkCzYphkTxziJioy7m1bIwyXmZY7wvxk59OGcATwQaSix5SCMDIsvhBhWbIOGy78LzV5Vd00sLMxL5PvqMMuyoMuVqBjXIPlso4Z0WZiKW2PZQPrlnOekfCizBmEkei3BRz9DebNYqiEdwIN85SZdObsK5LZKIDx4mbmpPmXjM3HFiDH/hYxe9Ek6gABGrIqiMo3i1zRxGBA1W2usvftW1Svc9kZM4XqpS+ELT6oXgieNQjBvhSVqAwD0iiOFhqdm/VtUs7cXOe6rgzK7jJxHOED3GWOU9 mac@MacBook-Pro-de-mac.local'   
